### ISSUE TITLE
Update for 2020

### ISSUE THREAD

**Issue by asteriskman7** [mevdschee/aoc-stats#2]
Please update this and the associated website (http://www.maurits.vdschee.nl/scatterplot/) to include 2020 data.

Would be great for the update to not require future changes just to add the next year.

**Comment by yarnnny** [comment]
Generic support for all of the upcoming AoC events could be a good idea. I think I can try to port this 🤔

**Comment by mevdschee** [comment]
There will always be manual work (as with any scraper). You can't foresee all the changes that EricW will make to his website (html/structure) in the upcoming years.

**Comment by mevdschee** [comment]
2020 and 2021 are added.
