### ISSUE TITLE
Please consider adding a license

### ISSUE THREAD

**Issue by jeroenheijmans** [mevdschee/aoc-stats#6]
As you know I love this work! Refer people to it every year.

Also every year I get back to #1 and for my own enjoyment I compare various years. But I guess it's technically not allowed as there's no license for the code in this repository.

Would you consider adding such a license, preferably one that would allow remixing? (Personally I'd be helped with just a license on the `index.html` and related files.)

**Comment by mevdschee** [comment]
>As you know I love this work! Refer people to it every year.

Thank you for your kind words.

>Also every year I get back to #1 and for my own enjoyment I compare various years.

I addressed this issue.

>Would you consider adding such a license

No, I'm sorry, I cant: I did not design the graphs nor is it my data.
